name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint (Ruff)
        run: ruff src

      - name: Format check (Black)
        run: black --check src

      - name: Unit tests
        run: pytest -q

      - name: Notebook smoke test
        run: |
          pytest --nbmake notebooks || echo "No notebooks found"
